const ACTION_TYPES = {
  UPDATE_CANDIDATE: 'UPDATE_CANDIDATE',
  UPDATE_CANDIDATE_CUSTOM_FORM: 'UPDATE_CANDIDATE_CUSTOM_FORM',
  OPEN_DIALOG: 'OPEN_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG',
  FOCUS_CELL: 'FOCUS_CELL',
  BLUR_CELL: 'BLUR_CELL',
  CREATE_TRANSACTION: 'CREATE_TRANSACTION',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  SET_VIEW: 'SET_VIEW',
  SET_VISIBLE_COLUMNS: 'SET_VISIBLE_COLUMNS',
  SET_NCCCO_TEST_FEES_CREDIT: 'SET_NCCCO_TEST_FEES_CREDIT',
  UPDATE_PRACTICAL_TEST_SCHEDULE: 'UPDATE_PRACTICAL_TEST_SCHEDULE',
  DELETE_PRACTICAL_TEST_SCHEDULE: 'DELETE_PRACTICAL_TEST_SCHEDULE'
};

export default ACTION_TYPES;
